# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-g7skHq6DfRZYjgFVVig6CyCsnROwKO
"""

#Import Library
import streamlit as st
import requests

#Buat Judul
st.title("Prediksi Tingkat Obesitas")

#Input
gender = st.selectbox("Gender", ["Male", "Female"])
age = st.number_input("Age", 1, 100)
height = st.number_input("Height (m)", 1.0, 2.5)
weight = st.number_input("Weight (kg)", 20.0, 300.0)
family = st.selectbox("Family History with Overweight", ["yes", "no"])
favc = st.selectbox("Frequent High Caloric Food", ["yes", "no"])
fcvc = st.number_input("Vegetable Intake Frequency", 1.0, 3.0)
ncp = st.number_input("Main Meals per Day", 1.0, 10.0)
caec = st.selectbox("Snacking Frequency", ["no", "Sometimes", "Frequently", "Always"])
smoke = st.selectbox("Smoke", ["yes", "no"])
ch2o = st.number_input("Water Intake", 1.0, 3.0)
scc = st.selectbox("Calories Monitoring", ["yes", "no"])
faf = st.number_input("Physical Activity (0-3)", 0.0, 3.0)
tue = st.number_input("Technology Use (0-3)", 0.0, 3.0)
calc = st.selectbox("Alcohol", ["no", "Sometimes", "Frequently", "Always"])
mtrans = st.selectbox("Transportation", ["Automobile", "Bike", "Motorbike", "Public_Transportation", "Walking"])

if st.button("Predict"):
    input_data = {
        "Gender": gender,
        "Age": age,
        "Height": height,
        "Weight": weight,
        "family_history_with_overweight": family,
        "FAVC": favc,
        "FCVC": fcvc,
        "NCP": ncp,
        "CAEC": caec,
        "SMOKE": smoke,
        "CH2O": ch2o,
        "SCC": scc,
        "FAF": faf,
        "TUE": tue,
        "CALC": calc,
        "MTRANS": mtrans
    }

#Mengirim data ke API dan menampikan prediksi
    try:
        response = requests.post("http://127.0.0.1:8000/predict", json=input_data)
        result = response.json()
        st.success(f"Hasil Prediksi: {result['prediction']}")
    except:
        st.error("Gagal menghubungi API backend.")